### ISSUE TITLE
Feature request - Warning consequences

### ISSUE THREAD

**Issue by jqzua** [Synapz1/WarningManager#1]
Hello,

I'm trying your plugin, but I miss the posibility to automatically show a message, kick or ban a player depending on how many warns he has received.
It would be very useful if could be configured at config.yml.

Also, it would be more useful if you could use /warn command instead /warning warn.

Thank you!

**Comment by Synapz1** [comment]
Thanks for the feed back. 
First, I will remove all the sub commands. This way you dont have to type /warning before everything. So you just type /reset, /warn, or /warnings. I was thinking about doing this but never changed it because I wasnt sure if I should, so thanks for that.

I have been working on how to automatically punish a player based on their warnings. I even have a version of WarningManager doing this how ever the punishments are hard coded and cant be configured. I was thinking about making a way in config for this. 
Something like this:
Punishments:
  2:
    command: /kick %PLAYER% Stop breaking rules.
  5: 
    command: ban %PLAYER% Auto banned, cool yourself.
This means every 2 warnings they will be auto kicked, and every 5 warnings they will be auto banned. This sound good?

Also I will be fixing the layouts of messages the plugin sends. Ive been busy on my other plugins I havent had time to update and fix this plugin. Thanks for your feed back Ill get to it soon.

**Comment by jqzua** [comment]
Thank you for your fast response.

I think that only /reset command could get in conflict with other plugins. I would use /warn to warn people and leave the other commands with /warning before for better compatibility with other plugins.

That sounds great! Number of warnings would be also configurable? It's exactly what I was looking for!

Thank you for your work!

**Comment by Synapz1** [comment]
Fixed commands and help menu. Here's how it now looks:
![New help menu](http://i.imgur.com/Ik7fH4L.png)
- As you can see, I made some of the commands less ambiguous by adding a 'w' in front of them, this way they don't collide with other commands like /reload or /help. 
- I replaced /warnings with /whelp, because I am not using sub commands anymore and it would better serve as a help menu. Because '/help WarningManager' does not show command arguments I left '/whelp' to show the arguments so it shows Admins how to use commands.
- I restructured the whole plugin so it's easier for me to update and fix bugs later on, this took my awhile but it is now better off.
- Updated the help menu with the new commands and fixed the header to look nicer.

I will continue tomorrow to add the configuration for setting punishments.

**Comment by Synapz1** [comment]
Plugin now has an auto punishment system in config.yml. 
You can download this stable version here:
https://github.com/Synapz1/WarningManager/releases/tag/1.2
Until I get it approved by BukkitDev.
